### ISSUE TITLE
Windows version. UI problem

### ISSUE THREAD

**Issue by pwitkowski1994** [CrealityOfficial/CrealityPrint#158]
Hi,

Problem is with
-size of ui window, cannot maximilize
-problem with cursor, it is offset against window

**Comment by pwitkowski1994** [comment]
![cp_503_ui_problem](https://github.com/CrealityOfficial/CrealityPrint/assets/72357532/52a4d0be-936b-4db8-aba7-aaf74a7fa933)

**Comment by carlos-chierici** [comment]
Same problem here - using v5.0.3.

**Comment by mattmaltarich** [comment]
Same issue on Windows.  Makes the software unusable. Your cursor has to be about half an inch above whatever you are trying to click to get it to activate.  Went back to the old version.  Looked cool, but not usable in this version.  Looking forward to an update.

**Comment by SHD3R** [comment]
I have exactly the same problem on 5.0.0, 5.0.2 and 5.0.3

**Comment by louisbotha** [comment]
Same issue, I have a monitor with a high aspect ratio. Make the app useless.

**Comment by Faz3270** [comment]
As anyone found a fix for this issue on Windows 10? desktop pc and laptop both the same, I've tried a few things but its still the same.
come on Creality fix this please!

**Comment by craig-childs** [comment]
Ditto, 
Windows 11, Creality Print v.5.0.0.8636
Screen resolution 1366 x 768, Samsung laptop integrated display.
Device name	Laptop-Samsung-NP300C
Processor	Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz   2.50 GHz
Installed RAM	6.00 GB (5.79 GB usable)
System type	64-bit operating system, x64-based processor

Software unusable!

**Comment by DoinStuff35** [comment]
Same hier / Win 10

**Comment by SHD3R** [comment]
Still does not work with the latest release 5.0.3.8733 from July 24. This is how it looks on full screen. It is completely unusable.
![image](https://github.com/CrealityOfficial/CrealityPrint/assets/5188191/9b1fc6fb-e14f-4c78-a6c9-39863f2fd77a)

**Comment by DAF54** [comment]
The lower right corner preview window is totally useless in Mac and Windows versions, it is does preview at all, the window is cut off and hidden due to the bug ridden application scaling screen size and UI issues. Application scaling and sizing bug that has been an issue since the first release. running application full screen by dragging application window to size needed crashes the application and turns the entire screen white.. all bugs and issues still unresolved in V5.0.3.8744 Mac and Windows..

**Comment by DAF54** [comment]
PLEASE ADDRESS THE BASIC UI AND SCALING ISSUES FOR THE APPLICATION WINDOW

**Comment by GC1268** [comment]
Same problem, sort of
Version 5.0.3
Windows 11

I had the same issue on first installing, did some searching and found comments about changing display settings in the app properties.  went in had a look made some changes and the bottom right corner seems to be right??
However when I click the LAN printing button, that window doesn't load properly, it didn't from the off.  Changed any changes for the display in the app properties back to what they were originally and the bottom right corner stayed as image below.

![Screenshot 2024-06-30 111423](https://github.com/CrealityOfficial/CrealityPrint/assets/174221248/b897458e-f987-49a3-9e3f-264d6d8c41b1)

![Screenshot 2024-06-30 111608](https://github.com/CrealityOfficial/CrealityPrint/assets/174221248/02b7a06c-2791-41df-9cc4-bfd85f341005)

**Comment by orangeworx** [comment]
Ditto what everyone said. This started with 5 and every update since hasn't addressed the issue... always go about half an inch higher, unless it's for any pop up window.

**Comment by carlos-chierici** [comment]
Creality launched Creality Print v5.1.1.9490 and this problem still remains...

**Comment by orangeworx** [comment]
Updated, again, issue remains.
This is quite frustrating.

**Comment by SHD3R** [comment]
Problem is finally fixed in the latest 5.1.2.9904 release - "Addressed an issue where mouse pointer offset in certain graphics card environments caused functionality buttons to be unclickable."

You can get it from CrealityCloud - https://www.crealitycloud.com/software-firmware/software/creality-print

**Comment by edgedj** [comment]
Still a problem with V5.1.4.10249 for me on a fairly old Fujitsu tablet with an integrated Intel 620 graphics card. Ideally this would work as I do drawing on my more powerful machines and this sits next to my K1C sending the print files

**Comment by twistedsanity** [comment]
Guess this issue may also be related to the scaling as I use a 7680x1440 display and the app opens full screen. When reducing to a more usable size the top row of buttons become so small they are almost unusable.
![image](https://github.com/user-attachments/assets/3b2275d8-8426-49e1-90b8-be752ac2bd7f)

**Comment by twistedsanity** [comment]
Just install v5.1.7.10514-win64-release and my scaling issues with the toolbar have been resolved. I wonder if the other items also a fixed but the same release.
